### PR TITLE
add legacyjavafixer

### PR DESCRIPTION
**Pull request by DioEgizio**

### CODE REVIEW

**Comment by Scrumplex** [comment]
Maybe some extra text like 

> Minecraft Forge provides a coremod, to fix some issues with older Forge versions on recent Java versions. You can download it here: \<url\>

**Comment by DioEgizio** [comment]
ok

**Comment by d-513** [comment]
Wait does this fix the java stuff where you have to update forge on 8u312 or higher

**Comment by DioEgizio** [comment]
no, it fixes java 8 on ancient MC versions when using forge like 1.6

**Pull request merged**
